apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ppg0pauhk-nodejs
  janus-idp.io/tekton: ppg0pauhk-nodejs
  backstage.io/kubernetes-id: ppg0pauhk-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ppg0pauhk-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
