apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ppg0pauhk-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ppg0pauhk-nodejs 
  name: ppg0pauhk-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ppg0pauhk-nodejs 
